aux_links:
  "Neuron Project": 
    - "https://github.com/neuronlabs"
  "Core": 
    - "https://github.com/neuronlabs/neuron-core"
  "Gateway": 
    - "https://github.com/neuronlabs/neuron-gateway"
  "PQ Repository":
    - "https://github.com/neuronlabs/neuron-pq"
  "Mongo Repository":
    - "https://github.com/neuronlabs/neuron-mongo"
plugins:
  - jekyll-relative-links
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
theme: "just-the-docs"
relative_links:
  enabled: true
  collections: true
